// The Fair Test — prove the second brain is cheaper AND faster than default,
// with numbers you can rerun. For each question we compare:
//   • brain path  — deterministic retrieval → a small evidence slice
//   • naive path  — the honest "no second brain" baseline: load the whole
//                    knowledge base into context (what a fresh session does when
//                    it has no index to tell it which file, which section).
// We report the token reduction (the headline: memory/claude-usage multiple),
// a conservative file-vs-section ratio, wall time, and whether the brain's
// evidence actually contains the correct answer. Nothing is generated by a model.
import fs from 'node:fs';
import path from 'node:path';
import { retrieve } from './retrieve.js';
import { estTokens } from './tokens.js';

const read = (dir, file) => fs.readFileSync(path.isAbsolute(file) ? file : path.join(dir, file), 'utf8');
const median = (xs) => { if (!xs.length) return 0; const s = [...xs].sort((a, b) => a - b); const m = s.length >> 1; return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2; };

function correctness(r, s) {
  if (s.expectId) return r.chosen?.id === s.expectId || r.pointer?.id === s.expectId;
  if (s.contains) return r.evidence.toLowerCase().includes(String(s.contains).toLowerCase());
  if (s.containsAny) return s.containsAny.some((c) => r.evidence.toLowerCase().includes(String(c).toLowerCase()));
  return !!r.chosen;
}

export function runBench(index, scenarios, { dir = index.dir } = {}) {
  // The no-retrieval baseline: the entire store loaded into context, timed.
  const t0 = process.hrtime.bigint();
  const allText = index.all().map((e) => read(dir, e.file)).join('\n\n');
  const naiveMs = +(Number(process.hrtime.bigint() - t0) / 1e6).toFixed(3);
  const storeTokens = estTokens(allText);

  const rows = scenarios.map((s) => {
    const r = retrieve(index, s.question);
    const brainTokens = r.tokens || 1;
    const fileTokens = r.chosen ? estTokens(read(dir, r.chosen.file)) : storeTokens;
    return {
      question: s.question,
      chosen: r.chosen?.id || null,
      pointer: r.pointer?.id || null,
      correct: correctness(r, s),
      brainTokens, fileTokens,
      reductionVsStore: +(storeTokens / brainTokens).toFixed(1),
      reductionVsFile: +(fileTokens / brainTokens).toFixed(1),
      brainMs: r.ms,
    };
  });

  const correct = rows.filter((r) => r.correct).length;
  return {
    total: rows.length, correct,
    storeTokens, storeMemories: index.all().length,
    medianBrainTokens: median(rows.map((r) => r.brainTokens)),
    medianTokenReduction: median(rows.map((r) => r.reductionVsStore)),
    medianReductionVsFile: median(rows.map((r) => r.reductionVsFile)),
    medianBrainMs: +median(rows.map((r) => r.brainMs)).toFixed(3),
    naiveMs, rows,
    pass: correct === rows.length && median(rows.map((r) => r.reductionVsStore)) >= 5,
  };
}

/** Fallback scenarios derived from the index when no bench.json exists. Each
 *  asks about a memory using words from its summary and expects that memory
 *  (or a pointer) to supply the answer. */
export function defaultScenarios(index) {
  return index.all().slice(0, 12).map((e) => ({
    question: `${e.name}: ${e.summary}`.slice(0, 120),
    expectId: e.id,
  }));
}

export function renderBench(report) {
  const L = [];
  L.push(`FAIR TEST — brain path vs. loading the whole knowledge base`);
  L.push(`  store: ${report.storeMemories} memories, ~${report.storeTokens} tokens if dumped into context`);
  L.push(`  questions: ${report.total}   correct: ${report.correct}/${report.total}`);
  L.push(`  median evidence: ~${report.medianBrainTokens} tokens   median reduction: ${report.medianTokenReduction}× vs full store, ${report.medianReductionVsFile}× vs whole best file`);
  L.push(`  retrieval: ${report.medianBrainMs}ms median   (loading the whole store took ${report.naiveMs}ms)`);
  L.push(`  VERDICT: ${report.pass ? 'PASS — cheaper (≥5×) and every answer correct' : 'not yet — keep optimising'}`);
  L.push('');
  L.push(`  ${'question'.padEnd(46)} ${'hit'.padEnd(22)} ${'tok'.padStart(5)} ${'×store'.padStart(7)} ${'ok'}`);
  for (const r of report.rows) {
    L.push(`  ${r.question.slice(0, 46).padEnd(46)} ${String(r.chosen || '—').slice(0, 22).padEnd(22)} ${String(r.brainTokens).padStart(5)} ${String(r.reductionVsStore).padStart(7)} ${r.correct ? '✓' : '✗'}`);
  }
  return L.join('\n');
}
